name: Add labels according to Issue title

on:
  workflow_call:
    secrets:
      token:
        description: "Github token"
        required: true
      repo:
        description: "Github repository"
        required: true

jobs:
  add-label-using-github-script:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    # permissions:
    #   issues: write
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            /**
             * @typedef {Object} Label
             * @property {string} regex - 検索文字列
             * @property {string} label - ラベル名
             *
             * TODO: inputs.jsonの読み込み形式に変更したい
             */
            /** @type {Label[]} */
            const labels = [
              { regex: /fix/, label: 'bugs 🐞' },
              { regex: /chore/, label: 'chore 🏠' },
              { regex: /feat/, label: 'enhancement 🚀' },
              { regex: /refactor/, label: 'refactoring 🧰' },
              { regex: /test/, label: 'testing ✅' },
              { regex: /design/, label: 'design 🏗️' },
              { regex: /docs/, label: 'docs ✍️' },
              { regex: /adr/, label: 'ADR 🏯' },
            ];

            const issueTitle = context.payload.issue.title;
            const labelsToAdd = [];

            labels.forEach(label => {
              if (label.regex.test(issueTitle)) {
                console.log(`Match: ${label.label}`);
                labelsToAdd.push(label.label);
              }
            });

            if (labelsToAdd.length > 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: labelsToAdd
              });
            }
            console.info(`title: ${issueTitle}, labels: ${labelsToAdd.join(',')}`);
