name: add milestone to Issue
on:
  workflow_call:
    inputs:
      number:
        description: "Issue number"
        required: true
        type: number
      milestone:
        description: "milestone"
        required: true
        type: string
    secrets:
      token:
        description: "Github token"
        required: true
      repo:
        description: "Github repository"
        required: true

jobs:
  add-milestone:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Add milestone to issue
        run: gh issue edit $NUMBER -m $MILESTONE
        env:
          GH_TOKEN: ${{ secrets.token }}
          GH_REPO: ${{ secrets.repo }}
          NUMBER: ${{ inputs.number }}
          MILESTONE: ${{ inputs.milestone }}
