name: Edit Issue using Github CLI
on:
  workflow_call:
    inputs:
      number:
        description: "Issue number"
        required: true
        type: number
      assignee:
        description: "Assign Issue author"
        required: false
        type: string
      title:
        description: "Issue title"
        required: false
        type: string
      milestone:
        description: "milestone"
        required: false
        type: string
    secrets:
      token:
        description: "Github token"
        required: true
      repo:
        description: "Github repository"
        required: false

jobs:
  edit-issue:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    env:
      NUMBER: ${{ inputs.number }}
    steps:
      - name: Add milestone
        if: ${{ inputs.milestone != 0 }}
        run: gh issue edit $NUMBER -m $MILESTONE
        env:
          GH_TOKEN: ${{ secrets.token }}
          GH_REPO: ${{ secrets.repo }}
          MILESTONE: ${{ inputs.milestone }}
      - name: Assginees
        if: ${{ inputs.assignee != 0 }}
        run: gh issue edit $NUMBER --add-assignee $ASSIGNEE
        env:
          GH_TOKEN: ${{ secrets.token }}
          GH_REPO: ${{ secrets.repo }}
          ASSIGNEE: ${{ inputs.assignee }}
