name: Add labels to Pull Requests using labeler
on:
  workflow_call:
    inputs:
      config-path:
        description: "The path to the labeler configuration file"
        required: true
        type: string
        default: ".github/labeler.yml"
    secrets:
      token:
        required: true

jobs:
  add-labels:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    outputs:
      LABELS: ${{ steps.labeler.outputs.all-labels }}
    steps:
      - id: labeler
        uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          repo-token: ${{ secrets.token }}
          configuration-path: ${{ inputs.config-path }}
      - name: Echo
        run: echo $LABELS
