name: Add labels to Pull Requests using labeler
on:
  workflow_call:
    inputs:
      config-path:
        description: "The path to the labeler configuration file"
        required: true
        type: string
        default: ".github/labeler.yml"
    secrets:
      token:
        required: true

jobs:
  add-labels:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    outputs:
      LABELS: ${{ steps.labeler.outputs.all-labels }}
    steps:
      - id: labeler
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: ${{ secrets.token }}
          configuration-path: ${{ inputs.config-path }}
      - name: Echo
        run: echo $LABELS
