name: Edit Pull Requests using Github CLI
on:
  workflow_call:
    inputs:
      number:
        description: "PR number"
        required: true
        type: string
      assignee:
        description: "Assign PR author"
        required: false
        type: string
      title:
        description: "PR title"
        required: false
        type: string
      milestone:
        description: "PR milestone"
        required: false
        type: string
    secrets:
      token:
        description: "Github token"
        required: true
      repo:
        description: "Github repository"
        required: true

jobs:
  edit-pr:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    env:
      NUMBER: ${{ inputs.number }}
    steps:
      - name: Assgin PR author
        run: gh pr edit $NUMBER --add-assignee $ASSIGNEE
        env:
          GH_TOKEN: ${{ secrets.token }}
          GH_REPO: ${{ secrets.repo }}
          ASSIGNEE: ${{ inputs.assignee }}
      - name: Add milestone
        run: gh pr edit $NUMBER -m $MILESTONE
        env:
          GH_TOKEN: ${{ secrets.token }}
          GH_REPO: ${{ secrets.repo }}
          MILESTONE: ${{ inputs.milestone }}
