name: Renovate validate workflow
on:
  workflow_call:
    secrets:
      token:
        description: "Github token"
        required: true

jobs:
  validate:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: 🤖 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧪 Test validation
        run: npm test
