name: Renovate validate workflow
on:
  workflow_call:
    secrets:
      token:
        description: "Github token"
        required: true

jobs:
  validate:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 🤖 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧪 Test validation
        run: npm test
